/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type EnigoJs = Enigo
export class Enigo {
  constructor()
  mouseClick(button: string): void
  mouseMoveTo(x: number, y: number): void
  mouseLocation(): Int32Array
}
